### PR TITLE
add beforeNow & afterNow rules

### PR DESCRIPTION
**Pull request by amelon**
add date relative rules: `afterNow` `beforeNow`

Often (at least in my case), date rules are relative to now.

``` js

var indic = new(require('indicative'));
var moment = require('moment');

var rules = {
    exp_date: 'afterNow:12,months'
};

var data = {
   exp_date: moment().add(14, 'months').toISOString()
};

indic.validate(rules, data)
.then(function() { // valid data });
```

function arguments are 
- `offset` : positive or negative number
- `key`: key values of `moment().add` [add](http://momentjs.com/docs/#/manipulating/add)

If it suits you, could you please accept this PR.

Thanks

### CODE REVIEW

**Comment by thetutlage** [comment]
I believe method names have to little different , if i read them in english like `after now 12 months` makes less sense to me.

It should be something like `after offset of 12 months` , and `before offset of 12 months`

```
after_offset_of:12,months
```

```
before_offset_of:12,months
```

What you think ?

**Comment by amelon** [comment]
clearer, you're right.

I'm thinking about message handling too.

I've written some code that allow to show and format the pivot date.

``` js
var defaultMessages = {
  after_offset_of:  "Date must be after  {fmt:DD/MM/YYYY}",
  before_offset_of:  "Date must be before {fmt:DD/MM/YYYY}",
};
```

And implementation is 

``` js

function parseMsg(message, pivot) {
 var matched = /.*\{(fmt:?([\w\s\\\/-]*))\}/.exec(message),
     dateFormat = 'YYYY-MM-DD';
 if (matched && matched.length && matched.length >= 3) {
   dateFormat = matched[2];
 }
  return message.replace(/(\{.*\})/, pivot.format(dateFormat));
}

function afterOffsetOf(data, field, message, args) {
  return new Promise(function(resolve, reject) {
    var pArgs = parseArgs(args),
        pivot, fieldValue;

    if (!R.has(field, data)) {
      return resolve("empty field");
    }
    fieldValue = moment(data[field]);
    pivot = moment().add(pArgs.offset, pArgs.key);
    if (fieldValue.isAfter(pivot)) {
      return resolve("is after offset");
    } else {
      return reject(parseMsg(message, pivot));
    }
  });
}
```

Do you think it is ok to add this stuff?

**Comment by thetutlage** [comment]
No this is very specific to this method only  and will confuse people as `api` has to be unified. I understand it takes the flexibility off but very customize things should be taken care at application level not at module level.

**Comment by amelon** [comment]
ok.
what do you suggest for displaying the pivot date the user?

**Comment by thetutlage** [comment]
You can make use of custom messages. Check them out here http://indicative.adonisjs.com/docs/node-validation-messages

**Comment by amelon** [comment]
Not clear for me.
I know the custom messages.
I don't understand how I can access the pivot date and show it in the message.

Can you make an exemple?

**Comment by thetutlage** [comment]
Haven't tried but this should work , and yes you have to require `moment` to the file where you are defining messages

```
Date should be after " + moment().add({{arg.0}},{{arg.1}}).format("DD/MM/YYYY")
```

**Comment by thetutlage** [comment]
Okay , i do not think there is any way to format message by passing it to `moment.format` , may be you have to do it manually.

``` javascript
var offset = '12'
var key = 'months'

var rules = {
  after_offset_of: offset + ',' + key
}

var messages = {
  after_offset_of: "Date should be after " + moment().add(offset,key).format("DD/MM/YYYY"))
}
```

**Comment by amelon** [comment]
yes, it looks better ;)

would you allow to have a message as a function that return a string?

``` js
var messages = {
  after_offset_of: function(rule, field, arrArgs, value) {
   return "Date should be after " + moment().add(arrArgs[0], arrArgs[1]).format("DD/MM/YYYY"))
 }
};
```

I know, I never stop :)

**Comment by thetutlage** [comment]
hahah , yes i was thinking about same. For now i think you have to go with custom solution, i have planned ton of changes on `indicative`, will do them soon.

And i am happy to accept the PR if you can change the function names

**Comment by amelon** [comment]
nice.
If you can share your plan it'll make me happy :)

I send you a new PR

**Comment by thetutlage** [comment]
sure i will soon , completing tasks list for http://adonisjs.com/ `v2` right now

**Comment by thetutlage** [comment]
Published `v1.3.0`

**Comment by thetutlage** [comment]
This may help you https://trello.com/b/wrAVl3FJ/indicative-2-0

**Comment by amelon** [comment]
remove coffee - youpi :)

I love trello
thanks and good night

**Pull request merged**
