### PR TITLE
feat(bundle): add rollup bundling process

### PR DESCRIPTION
**Pull request by RomainLanz**
Closes https://github.com/poppinss/indicative/issues/152

### CODE REVIEW

**Comment by thetutlage** [comment]
Ahhhh nice 👍

**Comment by RomainLanz** [comment]
Going to update it with ES6 import/export so tree-shaking will be possible 👍

**Comment by thetutlage** [comment]
Cool lemme push the serializers support and then you can do ahead

**Comment by thetutlage** [comment]
@RomainLanz Done with the formatters code. I am calling them `formatters` over `serializers`. Also I will be working in upcoming days to achieve following

1. Improve performance
2. Reduce size

Can u please complete the code for rollback, so that I can use that as the starting point

**Comment by thetutlage** [comment]
Closing since we got it in v4

**Pull request closed without merging**
