### PR TITLE
Feature/lowerCase & upperCase sanitizations

### PR DESCRIPTION
**Pull request by AndrewJo**
## Proposed changes

This PR adds support for adding `lowerCase` and `upperCase` sanitization rules. It can take in 1 optional argument for locale awareness. If argument is omitted, it will attempt to use the default system locale (see [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLocaleLowerCase)).

## Types of changes

What types of changes does your code introduce?

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/poppinss/indicative/CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by AndrewJo** [comment]
@thetutlage I reckon you've been pretty busy but if you can, please review this and #203 (which have been open since last year).

**Comment by thetutlage** [comment]
Thanks 😄

**Comment by zeeshanyshaikh** [comment]
How to use this? 
Am trying this in Adonis framework.

`  get sanitizationRules () {
    return {
      email: 'normalize_email',
      username: 'lowerCase'
    }
  }`

But its not working.. :( Is this change available in @adonisjs/validator v5.0.6 ?

**Comment by AndrewJo** [comment]
@zeeshanyshaikh unfortunately, no, this change isn't available in `@adonisjs/validator` v5.0.6. The changes in this PR only made it in to [v6.0.0](https://github.com/poppinss/indicative/commit/56df476f4997730d3b602c4f88d295359d9fd853) which was released just couple of weeks ago. Unfortunately, `@adonisjs/validator` v5.0.6 was released almost 6 months ago which was way before any of these improvements were merged in.

I believe @thetutlage has been busy overhauling AdonisJs to TypeScript (not to mention his day-to-day job) so you probably won't see the changes until he releases AdonisJs (or AdonisTs?) v5.

If you really need the features, my suggestion is to fork `@adonisjs/validator` and npm/yarn update to use `indicative` v6. Read the [`CHANGELOG.md`](https://github.com/poppinss/indicative/blob/56df476f4997730d3b602c4f88d295359d9fd853/CHANGELOG.md) for `indicative` v6 carefully for backwards breaking changes that you'll have to fix. Once you fix them, contribute and make the framework better for the community by submitting a pull request.

**Pull request merged**
