### PR TITLE
Replace `moment` with `date-fns`

### PR DESCRIPTION
**Pull request by Andreyco**
**Notes**
- `dateFormat(input: string, formats: any[], locale: string): boolean;` changed to `dateFormat(input: string, formats: any[]): boolean;` since this API was not exposed directly, nor documented. This change allows to drop locales import. It's possible to reexport locales provided by `date-fns`

### CODE REVIEW

**Comment by Andreyco** [comment]
cc @thetutlage

**Comment by thetutlage** [comment]
Have been going through the PR and the only breaking change I can see is that `date_format` will not working just with `time` anymore and always needs to have a date in front

**Comment by Andreyco** [comment]
@thetutlage yes, you are correct. Do you think watching for "time" format patterns and evaluating in different code path would be good solution? E.g.:

```js
// Pseudocode
Raw.dateFormat = function (input, formats) {
  const formatsArray = Array.isArray(formats) ? formats : [formats]
  return formatsArray.some(pattern => {
    return isTimeFormat(pattern))
        ? isValidTime(parseTime(input)) && format(input, pattern) === input
        : isValidDate(parseDate(input)) && format(input, pattern) === input
  })
}
```

Of would you prefer creating new "time_format" rule and keep "date_format" strictly for date validation?

**Comment by thetutlage** [comment]
Nope, I think it's fine to keep `time` separate from `date` and better have a different rule for time.

I am going merge the PR but will wait for a while to release it.

**Pull request merged**
