### PR TITLE
Feature/subset

### PR DESCRIPTION
**Pull request by AndrewJo**
## Proposed changes

This PR adds support for adding `subset` validator which is useful for [validating the `include` query string in JSONAPI](http://jsonapi.org/format/#fetching-includes):

> The value of the `include` parameter **MUST** be a comma-separated (U+002C COMMA, “,”) list of relationship paths. A relationship path is a dot-separated (U+002E FULL-STOP, “.”) list of [relationship](http://jsonapi.org/format/#document-resource-object-relationships) names.
>
> If a server is unable to identify a relationship path or does not support inclusion of resources from a path, it **MUST** respond with 400 Bad Request.

### Example usage:

Here's a contrived example:

```javascript
const rule = {
  include: 'subset:author,comments,comments.author'
}
```

If for example, the query string looks like: `include=author,comments.author`, the validation will pass. If however, the query string looks like: `include=invalid-relationship`, the validation will fail.

## Types of changes

What types of changes does your code introduce?

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/poppinss/indicative/CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation (if appropriate)

## Further comments

@thetutlage I only read the Contributing guidelines only after I finished this implementation and created this PR. I hope it's okay that I didn't create an RFC first as I wasn't aware before submitting this PR.

### CODE REVIEW

**Comment by thetutlage** [comment]
If I am not wrong, at-least one of the values has to match from the given subset right?

**Comment by AndrewJo** [comment]
Yes as long as it doesn't contain any values that's not in the superset. For example, if you have a rule:

```javascript
const rule = {
  numbers: 'subset:1,2,3,4,5'
}
```

Matches:
```javascript
const data = {
  numbers: [2, 1, 5]
}
```

But will throw validation message on:
```javascript
const data = {
  // 6 is not an element in the original array
  numbers: [1, 4, 3, 6]
}
```

It's most useful for matching whether multiple values are in a whitelist (versus `in` rule which only validates a single value in a list).

**Comment by thetutlage** [comment]
Looks beautiful 😄

**Comment by GuilhermeGuitte** [comment]
Cool! Any news about this feature?

**Review by RomainLanz — APPROVED** [review]

**Comment by AndrewJo** [comment]
@RomainLanz I just noticed you approved the PR. When can we expect to see this merged in?

**Comment by RomainLanz** [comment]
Hey @AndrewJo! 👋 

I don't have the right to merge this PR.
@thetutlage will probably do it when he has time to review it.

**Comment by AndrewJo** [comment]
Ah, got it. Thank you for the clarification! @RomainLanz

**Comment by thetutlage** [comment]
Sorry for getting late. At times, it's hard to look at Github notifications coz of all other work you have in life :)

**Comment by AndrewJo** [comment]
@thetutlage No worries 😄 I totally understand. I have few open source projects myself that I forget to check sometimes. :wink:

**Pull request merged**
