### PR TITLE
Lock `pope` to `1.0.2`. Version `1.0.3` breaks some tests.

### PR DESCRIPTION
**Pull request by Andreyco**
Also, introducing `yarn.lock` file, which would prevent this situation.

### CODE REVIEW

**Comment by RomainLanz** [comment]
Hey !

Please, remove `yarn.lock` and instead push the official lock file of `npm`.
Note that this issue of `pope` should be fixed soon.

**Comment by Andreyco** [comment]
NPM's `package-lock.json` is in place already.

Since Yarn is very popular, I think it's desired to keep `yarn.lock` for Yarn users.
`yarn.lock` guarantees everyone will get same install - package developer and end developer as well.

Please, propose further steps.

**Comment by Andreyco** [comment]
To note, when installed using NPM, correct dependency version is installed thanks to `package-lock.json`. Essentially, removing `yarn.lock` let installing broken dependency for Yarn users.

**Comment by thetutlage** [comment]
The answer is to fix the package that is breaking over adding unwanted layers. Yarn is something I do not use and popularity is not a metric to switch tools

**Comment by Andreyco** [comment]
> The answer is to fix the package that is breaking over adding unwanted layers. 

As long as you are an owner of package affecting other package. Would not be that easy if you do not have possibility to fix an issue, of wait ages to get merged.

> Yarn is something I do not use and popularity is not a metric to switch tools

I agree popularity is not a metric - quality is. And that's why I care about Yarn users as well as NPM users.

Therefore I strongly believe providing lock file for Yarn users is not unwanted layer, comparing to providing such solution for NPM users. 

_Notes:_ only NPM 5 users get benefit of lock file - plus early versions of NPM 5 had problems with lock file. Yarn, on the other hand, understands lock files from day one of it's existence.

**Pull request closed without merging**
